export const Extension = {
  0: 'server_name',
  1: 'max_fragment_length',
  2: 'client_certificate_url',
  3: 'trusted_ca_keys',
  4: 'truncated_hmac',
  5: 'status_request',
  6: 'user_mapping',
  7: 'client_authz',
  8: 'server_authz',
  9: 'cert_type',
  10: 'supported_groups (renamed from "elliptic_curves")',
  11: 'ec_point_formats',
  12: 'srp',
  13: 'signature_algorithms',
  14: 'use_srtp',
  15: 'heartbeat',
  16: 'application_layer_protocol_negotiation',
  17: 'status_request_v2',
  18: 'signed_certificate_timestamp',
  19: 'client_certificate_type',
  20: 'server_certificate_type',
  21: 'padding',
  22: 'encrypt_then_mac',
  23: 'extended_master_secret',
  24: 'token_binding',
  25: 'cached_info',
  26: 'tls_lts',
  27: 'compress_certificate (TEMPORARY - registered 2018-05-23, extension registered 2019-04-22, expires 2020-05-23)',
  28: 'record_size_limit',
  29: 'pwd_protect',
  30: 'pwd_clear',
  31: 'password_salt',
  35: 'session_ticket (renamed from "SessionTicket TLS")',
  41: 'pre_shared_key',
  42: 'early_data',
  43: 'supported_versions',
  44: 'cookie',
  45: 'psk_key_exchange_modes',
  47: 'certificate_authorities',
  48: 'oid_filters',
  49: 'post_handshake_auth',
  50: 'signature_algorithms_cert',
  51: 'key_share',
  52: 'transparency_info',
  65280: 'Reserved for Private Use',
  65281: 'renegotiation_info',
  65535: 'Reserved for Private Use (65282 - 65535)',
  // 46: 'Unassigned',
  // '32 - 34': 'Unassigned',
  // '36 - 40': 'Unassigned',
  // '53 - 65279': 'Unassigned',
}

// https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml
// https://tools.ietf.org/html/rfc4366
// https://tools.ietf.org/html/rfc3268#ref-SHA-1
// https://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.txt